### ISSUE TITLE
reproducing tetrodeplater

### ISSUE THREAD

**Issue by HDClark94** [MatsumotoJ/Tetroplater#2]
Hi, 

My lab is building this tetroplater from your designs so thank you very much for them! The dual power supply recommended isn't available, can you recommend an alternative?

Thanks!

**Comment by MatsumotoJ** [comment]
Thank you for your interest and infomation about the availability. 

- Previously I have tested with two 9V batteries:
https://www.instructables.com/id/Dual-Voltage-Supply-9V-batteries/

- This looks useful, although I have not tested:
Adafruit, Product ID: 2591, Switching Split Power Supply ± 12V 500mA Split Supply
https://www.adafruit.com/product/2591

- One contributor has suggested the circuit with the dual power supply but I still have not tried yet (see pull requests), so I am not sure for the function.

I hope the information would help.

**Comment by HDClark94** [comment]
Hi Jumpei,

Thank you for your quick response, we managed to source the original dual power supply but we are still having some issues. Would you care to look at this short youtube video and maybe suggest where we are going wrong? We're unclear why our input signal is being clipped.

https://www.youtube.com/watch?v=75SjV9040uI&feature=youtu.be

Best

Harry C

**Comment by HDClark94** [comment]
apologies, I uploaded the wrong video

this is the correct one

https://www.youtube.com/watch?v=yDl_W_UDG90&feature=youtu.be

**Comment by MatsumotoJ** [comment]
Hi, 

The input signal looks big.
Could you try to adjust oscillator amplitude (V_MEA_IN) to be 30~40 mVp-p by turning the trimmer potentiometer (R12; see readme.md).
Or you may re-check the resistance around the resistors around the op-amps for the amplification/attenuation of the signals.

Thank you for your time.

**Comment by HDClark94** [comment]
Thank you for your advice, we are making great progress now using the setup with the 9V batteries. and have brought our oscillator amplitude to 30-40mVp-p as suggested. 

We have observed the impedance of tetrodes to reduce with the a button push, however depending on the time it takes from connecting the tetrode to the gold plating solution and pushing the button, we observe the impedance to be lower if we wait for longer. This makes us think there could be some current flowing while the button is not pushed, is this possible? We were thinking this might be due to the noise of the output signal or perhaps a reaction between the metal contact from the BATH terminal and the gold plating solution (were seeing bubbles between the pin and the gold plating solution). And from our experience the very low impedances we're measuring (approximately 50kOhm compared to resistor references) typically suggests a shortcut.

We've made another video showing the main issue here :)
https://www.youtube.com/watch?v=PvQk7GQlNYQ&feature=youtu.be

Thank you for your help, it is really appreciated and we're almost there!

**Comment by MatsumotoJ** [comment]
I am happy to hear your progress. 

I guess that the push button might be soldered in the opposite direction. (https://www.nkkswitches.com/pdf/Gpushbuttons.pdf)

The button switches between plating (when button is down) and checking impedance (when button is released). In your video, the pattern looks opposite.

I hope that this could help.

**Comment by HDClark94** [comment]
Hi, 

We finally got it to work, the button was indeed the wrong way round, we wouldn't have noticed that if you hadn't had pointed it out. So thank you very much!

Its working great now. Best wishes!

**Comment by MatsumotoJ** [comment]
Nice!  I'm happy to hear that.
